spring:
  database:
    datasource:
      jdbc-url: jdbc:h2:mem:testdb;Mode=MYSQL;
      username: sa
      password:
      driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
# 파라미터 확인을 위한 trace
logging:
  level:
    org.hibernate.type: trace